name: remote ssh command

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: mdc.zeein.co.kr
        uses: appleboy/ssh-action@master
        with:
          host: mdc.zeein.co.kr
          username: zeein
          password: zeein39464000
          # key: ${{ secrets.KEY }}
          port: 2470
          script: |
            whoami
            cd /Users/violet/htdocs/zeeincokrmdc/wp-content/themes
            rm -rf zeein-mdc
            git clone https://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@github.com/zzin/mdc-studio.git zeein-mdc
